export type StitchRoute =
  | 'signin'
  | 'signup'
  | 'dashboard'
  | 'transactions'
  | 'analytics'
  | 'addExpense'
  | 'profile'
  | 'categories'
  | 'addCategory'
  | 'editCategory'
  | 'personalInfo'
  | 'budget'
  | 'notifications'
  | 'helpSupport'
  | 'welcome'
